<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AuraNetwork</AssemblyName>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <!-- Assembly/File version for updater checks -->
    <Version>8.62</Version>
    <AssemblyVersion>8.62.0.0</AssemblyVersion>
    <FileVersion>8.62.0.0</FileVersion>
    <InformationalVersion>8.62</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CmlLib.Core" Version="4.0.6" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\bg_music.mp3" />
    <EmbeddedResource Include="Resources\logo_small.png" />
    <EmbeddedResource Include="Resources\logo_large_new.png" />
    <EmbeddedResource Include="Resources\news_bg.jpg" />
  </ItemGroup>

</Project>
